name: Open URL on Successful Merge

on:
  push:
    branches:
      - main

jobs:
  open-url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Open URL on successful merge
      script: |
        curl -L -f -S -s https://himo.toolforge.org/update.php?user=1 > curl_output.txt || echo "Curl request failed with status code $?"
