name: Deploy via SSH # (1) Title of the action

on:
  push:
    branches:
      - main # (2) Name of the branch where the action should run

jobs:
  deploy:
    name: Deploy to SSH Server # (3) Title of the job
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          passphrase: ${{ secrets.TOOLFORGE_PASSPHRASE }}
          key: ${{ secrets.TOOLFORGE_PRIVATE_KEY}}
          port: 22
          request_pty: true
          script_stop: true
          # (4) Actual command(s) to run
          script: |
            become himo
            touch github_update.txt
            whoami
            # wget https://raw.githubusercontent.com/MrIbrahem/user-config/main/user-config.py -O /data/project/himo/user-config.py
            # wget https://raw.githubusercontent.com/MrIbrahem/user-config/main/user-config.py -O /data/project/sanaa/user-config.py
            # wget https://raw.githubusercontent.com/MrIbrahem/user-config/main/user-config.py -O /data/project/lyan/user-config.py
            # wget https://raw.githubusercontent.com/MrIbrahem/user-config/main/user-config.py -O /data/project/suha/user-config.py
            # wget https://raw.githubusercontent.com/MrIbrahem/user-config/main/user-config.py -O /data/project/nada/user-config.py
            # wget https://raw.githubusercontent.com/MrIbrahem/user-config/main/user-config.py -O /data/project/himowd/user-config.py
